### ISSUE TITLE
Question about the invalid url in `init()`

### ISSUE THREAD

**Issue by RManLuo** [sycny/RAE#3]
Thank you for open-sourcing your valuable code. However, the URL `https://quarry.wmflabs.org/run/45013/output/1/json`  is invalid and inaccessible. Could you please advise on how to access its content?

**Comment by sycny** [comment]
Hi, Thank you for being so interested in our work. This link is inaccessible due to some unknown reason. I have checked the code. I suggest to delete this line https://github.com/sycny/RAE/blob/82c6c647276f5677a57290fa95fe5133534ffc2f/wiki_api/wikidata.py#L114
This part is needed for something no longer in use. I will fix this issue as soon as possible. But you can try this out first.

**Comment by RManLuo** [comment]
Thanks a lot. I have deleted this part. It has been fixed.
