### ISSUE TITLE
Clarification on POS Reassignment in LemmaTokenize

### ISSUE THREAD

**Issue by SiyueTan07** [sycny/RAE#4]
Hello, 
I have a question regarding the LemmaTokenizer class in the wiki_api/strings.py file. Specifically, I am curious about the reassignment of the tag variable in the __call__ method.
![img_v3_02gh_8144be78-2e8f-425b-bb1d-3e61177397fg](https://github.com/user-attachments/assets/c79403cb-bee5-46d4-929a-e935754faf7f)

Could you please explain the reasoning behind this reassignment?  Thank you for your assistance.
Best regards

**Comment by JacksonWuxs** [comment]
Hi EntropyLix, 

Thanks for your attention to our work! 

We ask POS tagging to be VERB because we observe some cases in which the tagging process may introduce errors. These errors cause the lemmatizer to make a wrong decision in the following line. Since the major change in words is their verb format, we simplify the lemmatizing only to consider their verb forms. One example case is the common phrase "as soon as possible", where we observe that the second "as" is simplified as "a" if we don't enforce it to only consider the verb format.

Thanks,
Xuansheng

**Comment by EntropyLix** [comment]
Thank you for your help with this issue! Your answer was very helpful and resolved my confusion. I really appreciate your time and support!

> Hi EntropyLix,
> 
> Thanks for your attention to our work!
> 
> We ask POS tagging to be VERB because we observe some cases in which the tagging process may introduce errors. These errors cause the lemmatizer to make a wrong decision in the following line. Since the major change in words is their verb format, we simplify the lemmatizing only to consider their verb forms. One example case is the common phrase "as soon as possible", where we observe that the second "as" is simplified as "a" if we don't enforce it to only consider the verb format.
> 
> Thanks, Xuansheng


Thank you for your help with this issue! Your answer was very helpful and resolved my confusion. I really appreciate your time and support!

**Comment by SiyueTan07** [comment]
> Hi EntropyLix,
> 
> Thanks for your attention to our work!
> 
> We ask POS tagging to be VERB because we observe some cases in which the tagging process may introduce errors. These errors cause the lemmatizer to make a wrong decision in the following line. Since the major change in words is their verb format, we simplify the lemmatizing only to consider their verb forms. One example case is the common phrase "as soon as possible", where we observe that the second "as" is simplified as "a" if we don't enforce it to only consider the verb format.
> 
> Thanks, Xuansheng

Thank you for your help with this issue! Your answer was very helpful and resolved my confusion. I really appreciate your time and support!
